# Generated by Django 5.2.13 on 2026-06-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='category',
            field=models.CharField(choices=[('food', '식비'), ('transport', '교통비'), ('cafe', '카페/간식'), ('shopping', '쇼핑'), ('culture', '문화생활'), ('subscription', '구독'), ('leisure', '여가비'), ('other', '기타')], max_length=20),
        ),
    ]
