# Generated by Django 5.2.13 on 2026-06-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dailyachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyachievement',
            name='daily_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='score',
            field=models.FloatField(default=60),
        ),
    ]
