# Generated by Django 5.2.13 on 2026-06-17 16:46

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customchallenge',
            name='bonus_score',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='customchallenge',
            name='expires_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(choices=[('food', '식비'), ('transport', '교통비'), ('cafe', '카페/간식'), ('shopping', '쇼핑'), ('culture', '문화생활'), ('subscription', '구독'), ('leisure', '여가비'), ('other', '기타')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customchallenge',
            name='category',
            field=models.CharField(choices=[('food', '식비'), ('transport', '교통비'), ('cafe', '카페/간식'), ('shopping', '쇼핑'), ('culture', '문화생활'), ('subscription', '구독'), ('leisure', '여가비'), ('other', '기타')], max_length=20),
        ),
    ]
