# Generated by Django 5.2.13 on 2026-06-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_customchallenge_bonus_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customchallenge',
            name='expires_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='groupscorehistory',
            name='score_delta',
            field=models.FloatField(),
        ),
    ]
